name: Caller Workflow

on:
  workflow_dispatch:

jobs:
  deploy:
    name: action_job
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: uso do workflow reutilizavel
      - uses: dsbnogueira/reusable-workflow/.github/workflows/reusable.yaml@main
